#pragma once

#define PLAYER_MAX_SPEED 500
#define PLAYER_ACC 1500
#define PLAYER_DEACC_K 1.5
#define PLAYER_INVUL 3
#define PLAYER_BLINK_FREQ 2
#define PLAYER_FIRE_CD 0.1
#define PLAYER_RESPAWN_TIME 5

#define ENEMY_MAX_SPEED 300
#define ENEMY_ACC 30000
#define ENEMY_OMEGA 1
#define ENEMY_HIT_POINTS 5
#define ENEMY_INVIL 1
#define ENEMY_BLINK_FREQ 2

#define BULLET_TTL 1
#define BULLET_SPEED 700
#define BULLET_SPAWN_X 0.85
#define BULLET_SPAWN_Y 0.5
#define BULLET_SPAWN_Z 1.2

#define PARTICLES_TTL 0.2

#define PARTICLES_UPGRADE 10

#define PARTICLES_PLAYER 150
#define PARTICLES_PLAYER_SPRAY 50

#define PARTICLES_GUN 5
#define PARTICLES_GUN_WIDTH 5
#define PARTICLES_GUN_SPRAY 300

#define PARTICLES_BULLET 10
#define PARTICLES_BULLET_SPRAY 200

#define PARTICLES_ENEMY 200
#define PARTICLES_ENEMY_SPRAY 30

#define PARTICLES_SPAWN 3
#define PARTICLES_SPAWN_SPRAY 100

#define WAVE_DELAY 3
#define WAVE_ENEMIES_DELAY 1
#define WAVE_ENEMY_PER_LVL 2

#define WAVE_OFF_WALL 70
#define WAVE_VELOCITY 300

#define UPGRADE_PROB 8
#define UPGRADE_RAD 2

#define OFF_SCREEN_COORD 1000
